### ISSUE TITLE
为什么不是给黑洞transfer而是调用合约abi

### ISSUE THREAD

**Issue by ranxi2001** [benjieming421/iost_evm#1]
为什么不是给黑洞transfer而是调用合约abi

**Comment by benjieming421** [comment]
调用合约Contract6vU3ZWL57jQeFpbuqUxQfL5PGeFJekWrDG2WVGjWqrKx里面有个mint函数你可以看看，函数里面除了你说的给黑洞transfer转1个iost还有其他私有授权操作。而不是只是转给黑洞transfer代币就可以的

**Comment by ranxi2001** [comment]
![image](https://github.com/benjieming421/iost_evm/assets/77790009/2401b363-b69c-40cc-b2e6-c70d36a6e66e)
虽然这边显示有success，但是返回值为空。而且区块浏览器并没有成功记录。
下面是一个成功的地址区块记录：https://www.iostabc.com/account/0xiost88?activetab=1&listtab=0&page=1&rowsPerPage=20
![image](https://github.com/benjieming421/iost_evm/assets/77790009/588d3dae-6a7b-4ee1-ac90-87b2c13011e8)

**Comment by benjieming421** [comment]
成功区块的调用
![image](https://github.com/benjieming421/iost_evm/assets/39157935/8928d2d3-c4c8-4203-bcec-2f137abf7f9d)
我的程序的 昨天晚上的调用
![image](https://github.com/benjieming421/iost_evm/assets/39157935/582d693b-8ee9-4fa2-87ab-afead7145f6f)
什么可以看到一模一样的调用但是执行出不同的姿态。只能说tm的这一条链很垃圾，自己开放的链性能自己都不熟悉。
总的来说就是你的记录还在处理，或者链宕机了没处理到你这条链。等这条公链回复了你再试试吧
![image](https://github.com/benjieming421/iost_evm/assets/39157935/4e3f6703-b50e-4a94-bd14-37511645c8c6)

**Comment by ranxi2001** [comment]
好的，谢谢你！

**Comment by benjieming421** [comment]
> 好的，谢谢你！

要不要留个联系方式，有空一起交流一下 开发脚本

**Comment by ranxi2001** [comment]
wechatid：Arespollo
position：浙大链协 core dev
